name: Create and publish Container Images

on:
  push:
    tags:
      - v*

jobs:
  build-container-images:
    if: ${{ github.owner }} == "varbhat"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the amd64 image
        run: docker buildx build --load --platform "linux/amd64" . --tag ghcr.io/varbhat/exatorrent:amd64

      - name: Build the arm64 image
        run: docker buildx build --load --platform "linux/arm64" . --tag ghcr.io/varbhat/exatorrent:arm64

      - name: Build the arm32(linux/arm/v7) image
        run: docker buildx build --load --platform "linux/arm/v7" . --tag ghcr.io/varbhat/exatorrent:arm32

      - name: Create Manifest and Push Image
        run: |
          docker manifest create ghcr.io/varbhat/exatorrent:latest ghcr.io/varbhat/exatorrent:amd64 ghcr.io/varbhat/exatorrent:arm64 ghcr.io/varbhat/exatorrent:arm32
          docker manifest push ghcr.io/varbhat/exatorrent:latest