name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "^18"
          cache: "npm"
          cache-dependency-path: "internal/web/package-lock.json"

      - name: Build Web UI
        run: make web-ci

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21.4"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
